### ISSUE TITLE
Stops working if window is left open for a while

### ISSUE THREAD

**Issue by lordlycastle** [babyman/quick-tabs-chrome-extension#288] opened 2019-11-08 10:25 UTC
I noticed this when I leave my PC on overnight and come back it stops working. I can type to search but it returns no results. The solution to fix it is to disable and re-enable the extension from settings. 

I'm using Vivaldi (Chromium) browser. 

I love the fuzzy search and would love a fix for it.

**Comment by oherst** [comment] 2019-12-11 16:21
I've been seeing this same issue. I tried to 'inspect popup' to see if there was anything in the console but it doesn't allow me to (the popup closes when you right click the icon). Is there a way to prevent it from closing?

**Comment by babyman** [comment] 2019-12-17 13:26
You can open the popup as a tab using:

chrome-extension://jnjfeinjfmenlddahdjdmgpbokiacbbb/popup.html 

Right now the tab will close as soon as it looses focus but you will be able to access the inspector tools.

**Comment by t3db0t** [comment] 2019-12-17 18:38
I've been having this issue for a while (no results), here's some console output:
```
Uncaught TypeError: Cannot read property 'title' of undefined
    at e (fuse.min.js:9)
    at Object.e.exports [as getFn] (fuse.min.js:9)
    at e.value (fuse.min.js:9)
    at e.value (fuse.min.js:9)
    at FuseSearch.searchTabArray (popup.js:874)
    at FuseSearch.AbstractSearch.executeSearch (popup.js:691)
    at performQuery (popup.js:628)
    at HTMLDocument.<anonymous> (popup.js:385)
    at j (jquery-3.2.1.min.js:2)
    at k (jquery-3.2.1.min.js:2)
```

**Comment by babyman** [comment] 2020-01-31 13:54
This is likely related to bug #300 as QT was not handling tab replacement at all, this was fixed in the latest release.  Please re-open this ticket if you notice the issue is not resolved.

Thanks everyone for taking the time to report and update on this 😄.

**Closed by babyman** 2020-01-31 13:54 UTC
