### ISSUE TITLE
Can't switch to "discarded" tabs

### ISSUE THREAD

**Issue by nanobrad** [babyman/quick-tabs-chrome-extension#300] opened 2020-01-21 15:50 UTC
I tried out an extension called Auto Tab Discard, which is supposed to use Chrome's built-in discard feature to reduce CPU and memory usage. Tabs stay in the tab bar, but aren't reloaded until clicked on.

I noticed this stopped Quick Tabs from switching to them even though they show up in the search pop-up.

Background.js console shows:
`Unchecked runtime.lastError: No tab with id: 4157.`

I'm not sure if QuickTabs can be updated to fix this or if this has broader implications or not.

**Comment by babyman** [comment] 2020-01-22 03:40
That's weird, I installed the extension and Quick Tabs seems to be working properly when it switches to discarded tabs.  Somehow a tab was closed without QT knowing, I'm not sure how that would have happened.

I'm running `Version 79.0.3945.130 (Official Build) (64-bit)` on a Mac.

Any thoughts on how best to reproduce this issue would be very helpful...

**Comment by NathanR-85** [comment] 2020-01-24 04:04
Same issue here, except I'm using The Great Suspender (also very popular).

Basically any suspended tab shows up but you can't click it.

**Comment by babyman** [comment] 2020-01-24 04:35
Thanks @NathanR-85, do you see the same Background.js console error?

`Unchecked runtime.lastError: No tab with id: ???.`

Also what OS are you running, not sure if that's part of the issue or not, does it always fail? or fail after your system has been running for a while?

I have installed The Great Suspender and will leave it running for a while to see if I can reproduce this issue...

**Comment by NathanR-85** [comment] 2020-01-24 04:46
I'm not sure how to check that honestly.

I'm on Sierra.

On The Great Suspender, you can force suspend a tab by right-clicking on the page. That will help you test quickly.

**Comment by babyman** [comment] 2020-01-24 12:30
I'm running Catalina.

I don't see any obvious issues when I suspend the tabs manually, I'll keep the extension running and see if I can reproduce the issue.

In your case if you start Chrome and suspend the tabs immediately do you experience the issue?

Do you have the "Apply Chrome's built-in memory-saving when suspending" setting checked in TGS?

Thanks

**Comment by NathanR-85** [comment] 2020-01-25 21:48
> In your case if you start Chrome and suspend the tabs immediately do you experience the issue?

Yes, just verified.

> Do you have the "Apply Chrome's built-in memory-saving when suspending" setting checked in TGS?

Yes. I also just tried with it unchecked and the situation looks exactly the same.

Thanks

**Comment by babyman** [comment] 2020-01-26 03:10
Cool, I'm seeing the issue locally too and it looks like the issue is a missing tab event listener (`onReplace(...)`).  I have some code I'm testing and if it looks good I'll try and get it released tomorrow.

Thanks for your help with this 👍

**Comment by NathanR-85** [comment] 2020-01-26 03:39
Amazing, I'm very excited for this. Thank you!

**Closed** 2020-01-27 04:29 UTC

**Comment by NathanR-85** [comment] 2020-01-28 08:26
This is fixed for me now - thank you!

**Comment by nanobrad** [comment] 2020-01-28 17:47
This also fixes Auto Tab Discard. Thanks!
