### ISSUE TITLE
Rendering issues

### ISSUE THREAD

**Issue by kalmdown** [babyman/quick-tabs-chrome-extension#168] opened 2017-04-05 22:30 UTC
Menu often renders badly...
![image](https://cloud.githubusercontent.com/assets/2244894/24729624/f358384c-1a13-11e7-84da-5284ae7d5e20.png)

![image](https://cloud.githubusercontent.com/assets/2244894/24729637/00453974-1a14-11e7-9080-9050cb686c21.png)

OSX 10.12.3 Chrome 57.0.2987.133 (64-bit) 

Other Extensions:
+ Flip It 1.4
1Password: Password Manager and Secure Wallet 4.6.3.90
AdBlock 3.9.1
AddThis - Share & Bookmark (new) 3.0.5
Amazon Assistant for Chrome 10.1610.8.120
Answers by Answers.com 1.0.5
Application Launcher for Drive (by Google) 3.2
Axure RP Extension for Chrome 0.6.2
Caret 1.6.25
Chrome Remote Desktop 57.0.2987.84
Cisco WebEx Extension 1.0.9
Clearly 10.6.1.8
DGExtension 7.2.0.23
Discover DevTools Companion 0.2.13
Entanglement 3.9.2
Evernote Web Clipper 6.12
FreshStart - Cross Browser Session Manager 1.6.1
Google Docs 0.9
Google Docs Offline 1.4
Google Drawings 1.1
Google Sheets 1.1
Google Slides 0.9
HTTPS Everywhere 2017.3.17
Linkclump 2.7.6
McAfee SECURE Safe Browsing 2.16
Pinterest Save Button 2.0.7
Plex 2.12.9
Print and Save to the cloud with CleanSave 4.8.4
Quick Tabs 2016.9.20
Resolution Test 2.2
Save to Google Drive 2.1.1
Save to Pocket 2.1.32
Send from Gmail (by Google) 1.16
Sketchpad 3.5 3.5.2.23
Spaces 0.22
TabJump - Intelligent Tab Navigator 0.7.9.2
The Great Suspender 6.21
TooManyTabs for Chrome 2.2
Window Resizer 1.9.1.5
Zotero Connector 4.0.29.11

**Comment by myhau** [comment] 2017-04-09 21:35
I have the same problem

System: macOS 10.12.4, Chrome 57.0.2987.133 (64-bit)

**Comment by TimNZ** [comment] 2017-04-20 04:18
This is a Chrome + rendered Mustache template issue.  

If I change this:
```
  document.getElementById("content-list").innerHTML = Mustache.to_html(
      document.getElementById('template').text, context
  );
```

to this:

```
    var a = Mustache.to_html(
        document.getElementById('template').text, context
    );
    document.getElementById("content-list").innerHTML = "<div><span style='font-size: 72px'>Hey!</span></div>";
```

then there is generally no issue apart from occasional visual glitch in popup window.

Chrome 57 does not like the rendered HTML of the Mustache template.

**Comment by TimNZ** [comment] 2017-04-20 04:23
Removing the 'tabs' section from the template fixes the rendering.

```
  {{#tabs}}
    <div class="item tab open {{urlStyle}}" id="{{id}}">
      <div class="{{tabImageStyle}}">
        <img src="{{templateTabImage}}" width="16" height="16" border="0">
      </div>
      <div>
        <div class="close" id="c{{id}}" title="{{closeTitle}}"></div>
        <div class="title"{{#tips}} title="{{{templateTitle}}}"{{/tips}}>{{{templateTitle}}}</div>
        {{#urls}}<div class="url">{{{templateUrl}}}</div>{{/urls}}
      </div>
    </div>
  {{/tabs}}
```

**Comment by TimNZ** [comment] 2017-04-20 04:41
Narrowed it down to this.

Doesn't happen on Windows, at least in a Parallels VM.

Is broken on Canary (60.x) on OS X

```
        <div class="close" id="c{{id}}" title="{{closeTitle}}"></div>
        <div class="title"{{#tips}} title="{{{templateTitle}}}"{{/tips}}>{{{templateTitle}}}</div>
        {{#urls}}<div class="url">{{{templateUrl}}}</div>{{/urls}}
```

**Comment by TimNZ** [comment] 2017-04-20 04:51
Fix.  
```
    setTimeout(function() {
        document.getElementById("content-list").innerHTML = Mustache.to_html(
            document.getElementById('template').text, context);
    },100);
```

**Comment by babyman** [comment] 2017-04-25 13:18
This is a duplicate of a longstanding chrome issue #91 so I will close it.

@TimNZ thanks for proposed fix, this seems like it may work given the latest comments in the Chrome bug tracker ( https://bugs.chromium.org/p/chromium/issues/detail?id=428044#c13 ).  To bad we have to slow things down to work around the issue.

E

**Closed by babyman** 2017-04-25 13:18 UTC

**Comment by TimNZ** [comment] 2017-04-25 18:02
Well, I figured out the issue+fix myself, but disappointed I didn't do a better google first to find it is  so commonly reported, and a long outstanding bug.
