### ISSUE TITLE
Search list empty

### ISSUE THREAD

**Issue by zeiphon** [babyman/quick-tabs-chrome-extension#251] opened 2019-02-12 04:55 UTC
Often when opening Quick Tabs and typing a search term, the search list will be empty.
This may be related to hibernating windows, or perhaps just after a length of time has passed.

I'm not sure if relevant, but the tab count indicator is often also orange when this issue occurs, and sometimes reads an incorrect tab amount (possibly double).

I have to disable and re-enable the extension for search to resume working correctly.

Using Windows 7 64bit, Chrome 71.0.3578.98 64-bit

**Comment by zeiphon** [comment] 2019-02-13 10:19
![image](https://user-images.githubusercontent.com/2609791/52704566-f9adcd00-2fd4-11e9-9bc3-816859e2f022.png)

Appears that the icon does not remain orange, but disabling and re-enabling the extension now shows "93" as the tab count.

**Comment by Wizek** [comment] 2019-02-17 00:59
I'm having the same issue, makes keyboard shortcuts unusable too. Requires reloading of the extension which makes the extension completely forget about tab order.

**Comment by zeiphon** [comment] 2019-02-17 08:00
Looking at the background.js for this extension, this error appears quite a lot:

```
Error in event handler for tabs.onRemoved: TypeError: Cannot read property 'id' of undefined
    at indexOfTab (chrome-extension://jnjfeinjfmenlddahdjdmgpbokiacbbb/background.js:362:26)
    at recordTabsRemoved (chrome-extension://jnjfeinjfmenlddahdjdmgpbokiacbbb/background.js:446:15)
    at chrome-extension://jnjfeinjfmenlddahdjdmgpbokiacbbb/background.js:550:5
```

In indexOfTab(tabId) that's here:
```javascript
function indexOfTab(tabId) {
  for(var i = 0; i < tabs.length; i++) {
    if(tabId === tabs[i].id) { // <-- Cannot read property 'id' of undefined
      return i;
    }
  }
  return -1;
}
```

I sometimes have to kill tabs using the chrome task manager. Could this be related?

**Comment by Wizek** [comment] 2019-02-19 06:57
@zeiphon Even if killing tabs is related, I can attest that the error on my end happens even when I don't kill tabs. I don't think I needed to kill any tabs in the last week or month.

**Comment by Wizek** [comment] 2019-02-19 07:02
I wish chrome made it easy to roll back to an earlier version of an extension that was known to not have an issue. Has happened other times too when I got auto-updated to buggy releases of other extensions.

In this case it is likely that the `January 30, 2019` release introduced this bug. @babyman, could we perhaps roll back that release by re-releasing the previous known-to-be good version until this gets fixed?

**Comment by silesky** [comment] 2019-02-21 17:35
Rather than restarting the extension: deleting the search entry, closing the Menu, then re-opening the menu works for me (as a temporary fix).

**Comment by Wizek** [comment] 2019-02-24 09:02
@silesky Could you make a short video of what you mean? I tried something similar a few times and it didn't work for me.

**Comment by apothegm** [comment] 2019-02-25 21:17
I've been having the exact same problem for a little while now. I haven't been able to figure out what causes it. I think it's more likely to happen when the # of tabs I have open at one time gets out of hand. For example, I have 63 open now. (yes I have a problem)

> Rather than restarting the extension: deleting the search entry, closing the Menu, then re-opening the menu works for me (as a temporary fix).

I wish this worked for me. I've usually disabled/re-enabled extension or I found that if I type in three spaces to look up tab history, those results will get returned and then I can clear out my search term, re-activate extension using shortcut and it starts showing tab results again.

**Comment by apothegm** [comment] 2019-02-27 23:12
![quick tabs no results bug](https://user-images.githubusercontent.com/12129089/53529657-4c01ea00-3abb-11e9-8656-a0e77810d7b1.gif)

**Comment by Wizek** [comment] 2019-02-28 08:36
By the way, could it be that all of us have enabled the 'remember search
term' option in the settings? I've tried turning it off now and the bug
seems to be less severe.

**Comment by MartinLichtblau** [comment] 2019-03-01 08:15
Since my PR #244 was merged on January 31.... 
1. You sure this bug first appeared after ~31.01 and not ~10.01?
2. Try turning off "Keep last searched string in search box". 
3. Try using a different Search Type. 
4. Does it throw an **Error** when the bug appears? 
    @zeiphon in the mentioned line `tabs[i]` never should be undefined, since you always have some tabs open, thus tabs[] should never be empty/null/undefined.
5. Providing a screenshot of your options page could help.

**Comment by amorpheus** [comment] 2019-03-05 15:16
The problem seems to be tied very tightly to remembering the search string. I only use this extension occasionally, so today it had a term from last week or something. It didn't display any of my open tabs when I emptied the field. So I played around with it a bit, my findings are as follows:

- restarting Chrome turns "keep last searched string in search box" back on
- if Chrome starts and the "last searched string" doesn't match any open tabs, the entire list is empty
- if Chrome starts and the "last searched string" matches any open tabs, the extension works as expected

**Comment by MartinLichtblau** [comment] 2019-03-05 16:20
@amorpheus You comment made me look into the code and I just realized that the all the if statements have the wrong syntax. In this case:
```javascript
function restoreLastSearchedStr() {
  var s = localStorage["restore_last_searched_str"];
  return s ? s === 'true' : true;
}
```
But the correct syntax is: ```condition ? exprTrue : exprFalse```

**Comment by silesky** [comment] 2019-03-05 16:30
I wouldn't write Javascript this way, but thia function works as expected.
It simply casts the localstorage value to a boolean and returns it.

**Comment by MartinLichtblau** [comment] 2019-03-05 16:39
@silesky Ohh, based on the syntax I thought it would always return true, and never false.

**Comment by silesky** [comment] 2019-03-05 17:08
@MartinLichtblau yes, you are correct! (sorry, early here). That looks like a bug!

should be `s ? s === 'true' : false`

**Comment by Wizek** [comment] 2019-03-20 19:00
This is getting ridiculous. I've reverted to default settings and even with that the bug persists. I'm going to downgrade to the 2018 version from here: https://crx.dam.io/ext/jnjfeinjfmenlddahdjdmgpbokiacbbb.html

Since that version didn't have any issues like this. I recommend you to do the same.

**Comment by MartinLichtblau** [comment] 2019-03-22 16:27
I would help, but I can't replicate the issue. Please provide more details.

**Comment by cwenner** [comment] 2019-04-27 15:44
Can verify that this issue happens quite frequently. Like @zeiphon mentioned, there are logs of undefined id. @MartinLichtblau's suggestions fix it temporarily - "Keep last searched string in search box" and/or "use a different Search Type".

**Comment by cwenner** [comment] 2019-04-27 15:48
2177 occurrences of undefined `id` on the following line:

```
function indexOfTab(tabId) {
  for(var i = 0; i < tabs.length; i++) {
    **if(tabId === tabs[i].id) {**
      return i;
    }
  }
  return -1;
}
```


Error in event handler: TypeError: Cannot read property 'id' of undefined
    at indexOfTab (<URL>)
    at recordTabsRemoved (<URL>)
    at <URL>
_generated_background_page.html:1 Error in event handler: TypeError: Cannot read property 'id' of undefined
    at indexOfTab (chrome-extension://jnjfeinjfmenlddahdjdmgpbokiacbbb/background.js:378:26)
    at recordTabsRemoved (chrome-extension://jnjfeinjfmenlddahdjdmgpbokiacbbb/background.js:469:15)

**Comment by cwenner** [comment] 2019-04-27 16:26
@MartinLichtblau - Logging `tabs` and will report back when it occurs again.

**Comment by jgfaust** [comment] 2019-05-31 03:00
This is an issue with maintaining a valid list of tabs.  I'll try to isolate it & submit a PR.  I think it's unrelated to search strings.

@zeiphon's [snippet](https://github.com/babyman/quick-tabs-chrome-extension/issues/251#issuecomment-464426865) is the most common symptom of the problem, but it's not the cause.  It's a symptom, just like the empty search list.

I can't give an exact cause other than that given enough time and enough tabs, the issue always occurs.  But we're talking over the course of days and routinely having hundreds of tabs.

This will occur on both Windows and Linux.  It's been happening since last year sometime.

May be identical:

https://github.com/babyman/quick-tabs-chrome-extension/issues/275

But _not_ these:

https://github.com/babyman/quick-tabs-chrome-extension/issues/232
https://github.com/babyman/quick-tabs-chrome-extension/issues/261

Aside: Thanks for actively maintaining this extension!  Please note that the published version of the extension in the Chrome Web Store is newer than the code found in this repository.  At least the version appears different.  If a maintainer could please get them in sync, it would help keep any contributors from missing any changes.  I have verified that the bug is present in both the Store version and this github repo.

**Closed** 2020-05-31 16:49 UTC
