### ISSUE TITLE
pop-up sizing incorrectly

### ISSUE THREAD

**Issue by rakslice** [babyman/quick-tabs-chrome-extension#100] opened 2015-10-19 23:33 UTC
Recently (maybe the past few chrome versions?) when I open quick tabs, the pop-up is very small, sometimes only one row tall, sometimes wide enough that I can see the results, and sometimes < 10 px wide.  This happens whether I open quick tabs with the keyboard shortcut or the toolbar button.

![quick tabs sizing issue](https://cloud.githubusercontent.com/assets/1845104/10594158/15095e88-767f-11e5-93b4-361ac886411c.png)

I just realized that this only occurs when the Chrome window is on my rightmost monitor, so this is easy to work around.

![multimonitor setup](https://cloud.githubusercontent.com/assets/1845104/10594253/fad8f0f4-767f-11e5-9d88-3aed4c6a1271.png)

**Comment by babyman** [comment] 2015-10-21 02:19
Looks like #91 is alive and well :|

**Comment by rakslice** [comment] 2015-10-24 04:32
I just observed one of my other Chrome extensions having the same problem, so this probably isn't a problem with quick tabs.

**Comment by babyman** [comment] 2017-01-14 22:07
I'm going to close this since it's a duplicate of #91, unfortunately this is still an issue.

**Closed by babyman** 2017-01-14 22:07 UTC
Labels: duplicate
