### ISSUE TITLE
Popup window is hidden when entering the page

### ISSUE THREAD

**Issue by afilp** [babyman/quick-tabs-chrome-extension#239] opened 2019-01-04 15:03 UTC
I use Chrome Version 71.0.3578.98 (Official Build) (64-bit)

After some time (not sure what causes it), the popup window is hidden so I cannot choose an item from the available choices:

![image](https://user-images.githubusercontent.com/7850073/50694409-7f3b7600-1042-11e9-9ff8-fe8312bb3c22.png)

Are you aware of this? Do you know what causes it and if there is a fix apart from closing all Chrome instances and restart it again?

Thanks!

**Comment by babyman** [comment] 2019-01-08 03:01
@afilp, thanks for taking the time to report your issue.  This looks like a duplicate of #91 which is still an open Chrome issue, I will close this bug but please reopen it if you think this is a new/separate issue.

Just to confirm, are you using OSX?

Evan

**Closed by babyman** 2019-01-08 03:01 UTC

**Comment by afilp** [comment] 2019-01-08 14:12
@babyman I am using Windows 10. Indeed, this seems to be the same as #91.
