### ISSUE TITLE
Keyboard shortcut ctrl + e doesn't work 

### ISSUE THREAD

**Issue by stevenqzhang** [babyman/quick-tabs-chrome-extension#141] opened 2016-07-13 00:55 UTC
After keyboard shortcuts in extensions became managed in Chrome instead of in the extension, ctrl + e (or any other shortcut) no longer work. Could the shortcut be trapped by another app or something?

Running Chrome Version 51.0.2704.103 (64-bit)

Mac OS X 10.11.3 El Cap #

**Comment by babyman** [comment] 2016-07-15 00:27
Does this happen after you have used the burger menu? 

My initial thought I'd that it's related to issue #123, this is a really frustrating issue that seems to be Mac specific and being ignored by the chrome guys :(

**Comment by stevenqzhang** [comment] 2016-07-16 18:23
Yes, that's exactly the repro! Restarting chrome fixes the issue.

**Comment by babyman** [comment] 2016-07-16 21:00
Sorry, I wish I could fix this one it's a real pain. I have just stopped using the burger menu :|

Duplicate of #123

**Closed by babyman** 2016-07-16 21:00 UTC
