### ISSUE TITLE
Temporary disappearance of the tab you switch from.

### ISSUE THREAD

**Issue by cloneman** [babyman/quick-tabs-chrome-extension#134] opened 2016-05-16 04:13 UTC
To keep it simple, let's say I have 3 tabs open. I activate the extension, and it shows me the two tabs that are in the background. This seems as expected.

Start at Tab 2.
I switch to tab 1 using Quick Tabs. Activate the extension - and Tab 2 is missing from list. Activate extension again, Tab 2 reappears (but now the selected tab is gone from the list).

So basically there is an inconsistency in the tab list when switching tabs. When switching to another tab, the previous tab temporary disappears from the list, and then when activating the extension again, it re-appears - replacing the current tab in the list.

Personally I prefer all tabs to be shown at all times, including the front most tab, however, even in case where this is not the desired design, it seems erroneous that the previously selected tab disappears from the list.
W10, Chrome 50.

**Comment by babyman** [comment] 2016-07-01 03:16
I think this is actually a duplicate of #103, let me know if I'm wrong.

**Closed by babyman** 2016-07-01 03:16 UTC
