### ISSUE TITLE
Opening: sometimes height is unusable

### ISSUE THREAD

**Issue by vitaly-zdanevich** [babyman/quick-tabs-chrome-extension#215] opened 2018-05-03 19:21 UTC
![quick-tabs-defect-opening](https://user-images.githubusercontent.com/3514015/39598135-34c130bc-4f20-11e8-97e0-e9113c81474e.gif)

**Comment by dchenbecker** [comment] 2018-05-09 17:32
Duplicate of #91

**Comment by babyman** [comment] 2018-11-27 12:42
Closing as duplicate.

**Closed by babyman** 2018-11-27 12:42 UTC
